[tool.poetry]
package-mode = false

[project]
name = "sample-streamlit"
version = "0.1.0"
description = ""
authors = [
    {name = "sakagami0615",email = "sakagami0615@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "streamlit (>=1.61.1,<2.0.0)",
    "pandas (>=3.0.5,<4.0.0)",
    "pydantic (>=2.9.0,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^9.1.1"

[tool.pytest.ini_options]
pythonpath = ["."]

